collections:
  tags:
    output: true
defaults:
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tagpage"
      title: "Chris Luedtke's Blog"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Chris Luedtke"
  - scope:
      path: ""
    values:
      layout: "default"