markdown: kramdown
highlighter: rouge
title: "Chris Luedtke"
subtitle: "Data Scientist for diverse problems and industries"
header_img: "/assets/images/home-bg.jpg"
author: "Chris Luedtke"
collections:
  tags:
    output: true
defaults:
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "home"
      title: "Chris Luedtke"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"